Models/ErrorViewModel.cs
using System;

namespace Ch26_Practice_2___Razor_Forms.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ch26_Practice_2___Razor_Forms.Controllers
{
    public class EventsController : Controller
    {
        static private Dictionary<string, string> Events = new Dictionary<string, string>();

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.events = Events;
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Route("/Events/Add")]
        public IActionResult NewEvent(string name, string description)
        {
            Events.Add(name, description);
            return Redirect("/Events");
        }



    }
}

Controllers/HomeController.cs
using Ch26_Practice_2___Razor_Forms.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Ch26_Practice_2___Razor_Forms.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("images/")]
        public IActionResult Images()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Events/Add.cshtml
<h1>Add Event and Description</h1>

<form method="post">
    <p>Event Name:</p>
    <input name="name" type="text" />
    
    <p>Event Description: </p>
    <input name="description" type="text" /> <!--input name="name"-->
    <br />
    <br />
    <input type="submit" value="Add Event and Description" /> 
</form>

Views/Events/Index.cshtml
<h1>Coding Events</h1>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>

@if (ViewBag.events.Count == 0)
{
    <p>No events yet!</p>
}

<!--
<ul>
    foreach (string meeting in ViewBag.events)
            {
                <li>meeting</li>
            }
</ul>
    -->

<table class="table">
    <thead>
        <tr>
            <th scope="col">Event</th>
            <th scope="col">Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (KeyValuePair<string, string> item in ViewBag.Events)
        {

        <tr>
            <td>@item.Key</td>
            <td>@item.Value</td>
        </tr>
        }
    </tbody>
</table>



<partial name="/Views/Shared/_LinkListPartial.cshtml" />

Views/Home/Images.cshtml
<!--<link rel="stylesheet" type="text/css" href="~/css/images.css""/>

<img src="~images/stockpeople.jfif" alt="Stock People gathered around computer" /> -->

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ch26_Practice_2___Razor_Forms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ch26_Practice_2___Razor_Forms</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link-text-dark" asp-area="" asp-controller="Events" asp-action="Add">Add an events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link-text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Ch26_Practice_2___Razor_Forms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LinkListPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<a href="https://www.launchcode.org">LaunchCode</a>
<br />
<a href="https://www.lego.com">Play Well</a>
<br />
<a href="https://www.webelements.com">Other Building Blocks</a>